# Minimal Beacon Chain Config for Local Testnet
PRESET_BASE: 'minimal'
CONFIG_NAME: 'local'

# Genesis
# ---------------------------------------------------------------
# [customized]
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 64
MIN_GENESIS_TIME: 0 
# GENESIS_FORK_VERSION: 0x00000001
GENESIS_DELAY: 0

# Forks
# ---------------------------------------------------------------
# [customized]
# ALTAIR_FORK_VERSION: 0x01000001
ALTAIR_FORK_EPOCH: 0
# BELLATRIX_FORK_VERSION: 0x02000001
BELLATRIX_FORK_EPOCH: 0
# CAPELLA_FORK_VERSION: 0x03000001
CAPELLA_FORK_EPOCH: 0
# DENEB_FORK_VERSION: 0x04000001
DENEB_FORK_EPOCH: 0

# Time parameters
# ---------------------------------------------------------------
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242 
