global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'geth'
    scrape_interval: 5s
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['geth:6060']

  - job_name: 'beacon'
    scrape_interval: 5s
    static_configs:
      - targets: ['beacon:8080']

  - job_name: 'validator'
    scrape_interval: 5s
    static_configs:
      - targets: ['validator:8081']
