global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'geth'
    scrape_interval: 5s
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['geth:6060']

  - job_name: 'prysm'
    scrape_interval: 5s
    static_configs:
      - targets: ['prysm:8080']
